
name: "タスク"
description: "開発以外の作業や小規模タスク"
title: "[タスク] 簡潔なタイトル"
labels: ["種別:タスク", "優先度:中"]
body:
  - type: input
    id: summary
    attributes:
      label: 概要
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: 作業内容
      placeholder: 作業の具体的な内容・手順
  - type: textarea
    id: done
    attributes:
      label: 完了条件
      placeholder: 何ができたら完了とみなすか
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - 高
        - 中
        - 低
