name: 作業チケット
description: 実装/設定/運用などの具体タスク
title: "chore: [領域] タスクの概要"
labels: [task]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      placeholder: 何を完了させるチケットですか？
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景/目的
      placeholder: なぜ必要？どの成果に紐づく？

  - type: textarea
    id: subtasks
    attributes:
      label: サブタスク
      description: チェックリスト形式で列挙してください
      placeholder: |
        - [ ] A を実施
        - [ ] B を確認
        - [ ] C をレビュー

  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ基準
      placeholder: 完了の定義（DoD）。レビュー観点・動作確認項目など

  - type: input
    id: due
    attributes:
      label: 期限（任意）
      placeholder: 例) 2025-09-30

  - type: input
    id: related
    attributes:
      label: 関連 Issue/PR
      placeholder: 例) #101 #202
